---
title: "About Me"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to my website! My name is Natalia Iannucci, and I am a Statistical & Data Sciences Student at [Smith College](https://www.smith.edu/academics/statistics) in Northampton, MA, graduating in 2022. I am also a member of the [Baumer Lab](https://baumer-lab.github.io/www/index.html), a data science research group at Smith College. I am also a Gold Key tour guide, and love showing others around my campus.

I use RStudio to create blog posts based on open-source data sets. These articles allow me to practice my R coding skills, as well as highlight my proficencies in data wrangling using dplyr an SQL, data visualization using ggplot, and coding capabilities. Please take a look at some posts to see some of my work that I have done in my free time.

I have taken SDS192 Introduction to Data Science, in which I learned and coding in R and data science skills to complete [assignments](https://github.com/niannucci/practice) and projects, including [data wrangling with dplyr](https://github.com/niannucci/sds192-mp2), [spatial data analysis using leaflet and ggplot](https://github.com/niannucci/MP3-Macleish), and [SQL querying](https://github.com/niannucci/MP4-querying). I have also completed CSC111, Introduction to Computer Science Through Programming, in which I learned Python.

This semester (Fall 2019), I am taking SDS291 Multiple Regression, SDS390 Topics in Data Science: Programming for Data Science, and MTH112 Calculus II.

You can find me on GitHub @niannucci, where I have repositories containing more of my work, including assignments and projects from my college courses, as well as the documentation and code for creating this website.
